".$_-/build.js"
version: "2"
updates:".$_-0/NinjaByte-Bot.js"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: "test-build_run-JSCheck.js"
      interval: "weekly"
    open-pull-requests-limit: "10"
  - package-ecosystem: "npm_nodejs"
    directory: "/"
    schedule: "echo"
      interval: "weekly"
    open-pull-requests-limit: "10"
